### ISSUE TITLE
Qt6 Camera lost frames

### ISSUE THREAD

**Issue by InterelectronixEK** [khomin/gstreamer-cpp-camera#1]
I tested with a USB camera (/dev/video0), which can video/x-raw and image/jpeg in different sizes and resolutions on Ubuntu 22.

If I start the application in QtCreator, the qml window pops up and the 2 image provider with the camera streams are visible.

After a short time, the window close and the following error message is shown in the application output:
```
SinkImage: : created
SinkImage: : created
SinkEncode: : created
SourceDecode: : created
SinkEncode: : GOT signal id: 94
0:00:00.994139517 191946 0x60adf9f84f00 WARN                 v4l2src gstv4l2src.c:1123:gst_v4l2src_create:<source_to_out> lost frames detected: count = 1 - ts: 0:00:00.697600048
BTEST: encode put sample capture: 1713941674543097049
BTEST: encode sample ready capture: 1713941674556612
BTEST: decode put sample capture: 1713941674556689597
BTEST: image sample capture: 19625
BTEST: decode sample ready capture: 20065732
SourceDevice: : destroyed
SinkImage: : destroyed
SourceDecode: : destroyed
SinkImage: : destroyed
SinkEncode: : destroyed, id: 94
SinkImage: : created
SinkImage: : created
SinkEncode: : created
SourceDecode: : created
SinkEncode: : GOT signal id: 103
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  62
  Current serial number in output stream:  62
```

Is it possible to use the MPEG output of the camera and use jpegdec in the pipeline?

The reason why I want to do this is, that with video/x-raw the framerate on higher resolutions is only 10 fps and with MPEG (image/jpeg) the framerate could be maximal 120 fps.

**Comment by khomin** [comment]
Oh, i don't know
That is my experiments, didn't think someone will find the repo )
I think it depends on the caps your camera generate data in
Likely it is raw data anyway
But you may try to change pixel format from RGB to yuv420
